# fly.toml app configuration file generated for echo-transcriber-bot on 2023-10-01T16:29:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "echo-transcriber-bot"
primary_region = "gru"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 443
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20